name: Deploy to Fission

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Install fission-cli
        run: |
          # Install Node.js first
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install fission-cli via npm
          sudo npm install -g fission-cli
          
          # Verify installation
          which fission
          fission version

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          ls -la $HOME/.kube/
          kubectl cluster-info
        continue-on-error: true

      - name: Apply Fission specs
        run: |
          ls -la ./specs/
          fission spec apply --specdir ./specs --wait
          
      - name: Test deployment
        run: |
          sleep 30
          curl -f http://fission-router.default.svc.cluster.local/hello || echo "Deployment test failed"


