name: Deploy to Fission

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Install fission-cli
        run: |
          # Install Go first
          sudo apt-get update
          sudo apt-get install -y golang-go git
          
          # Set Go environment
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          
          # Clone and build fission from source
          git clone https://github.com/fission/fission.git
          cd fission
          
          # Explore repository structure
          echo "=== Repository structure ==="
          ls -la
          echo "=== Looking for Go files ==="
          find . -name "*.go" | head -20
          echo "=== Looking for main.go files ==="
          find . -name "main.go" | head -10
          echo "=== Looking for cmd directories ==="
          find . -type d -name "cmd" | head -10
          echo "=== Contents of cmd directories ==="
          find . -type d -name "cmd" -exec ls -la {} \;
          
          # Try to find the correct path
          FISSION_PATH=$(find . -name "main.go" | grep -E "(cmd|cli|fission)" | head -1 | xargs dirname)
          echo "Found potential Fission CLI path: $FISSION_PATH"
          
          if [ -n "$FISSION_PATH" ]; then
            go build -o fission ./$FISSION_PATH
          else
            echo "Could not find Fission CLI path, trying alternative approach..."
            # Try building from root with specific target
            go build -o fission .
          fi
          
          # Install fission CLI
          sudo mv fission /usr/local/bin/fission
          
          # Create required directories for fission
          sudo mkdir -p /tmp/cli-docs
          sudo chmod 777 /tmp/cli-docs
          
          # Verify installation
          which fission
          fission version

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          ls -la $HOME/.kube/
          kubectl cluster-info
        continue-on-error: true

      - name: Apply Fission specs
        run: |
          ls -la ./specs/
          fission spec apply --specdir ./specs --wait
          
      - name: Test deployment
        run: |
          sleep 30
          curl -f http://fission-router.default.svc.cluster.local/hello || echo "Deployment test failed"


