name: Deploy to Fission

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Install fission-cli
        run: |
          # Install Docker first
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          
          # Create fission wrapper script
          sudo tee /usr/local/bin/fission > /dev/null << 'EOF'
          #!/bin/bash
          docker run --rm -it \
            -v ~/.kube:/root/.kube \
            -v ~/.fission:/root/.fission \
            fission/fission:latest \
            fission "$@"
          EOF
          
          sudo chmod +x /usr/local/bin/fission
          
          # Verify installation
          which fission
          fission version

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
          ls -la $HOME/.kube/
          kubectl cluster-info
        continue-on-error: true

      - name: Apply Fission specs
        run: |
          ls -la ./specs/
          fission spec apply --specdir ./specs --wait
          
      - name: Test deployment
        run: |
          sleep 30
          curl -f http://fission-router.default.svc.cluster.local/hello || echo "Deployment test failed"


